apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "greenbone.fullname" . }}-vt-data
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.vtData.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.vtData.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "greenbone.fullname" . }}-scap-data
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.scapData.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.scapData.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "greenbone.fullname" . }}-cert-data
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.certData.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.certData.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "greenbone.fullname" . }}-gvmd-data
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.gvmdData.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.gvmdData.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "greenbone.fullname" . }}-notus-data
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.notusData.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.notusData.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}

