{{/*
This is a sample template showing the structure of the single existingSecret
expected by the chart. It is disabled by default so it does not conflict with
your actual pre-existing secret.
*/}}
{{- if false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecret }}
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
type: Opaque
stringData:
  # The keys below match the default values in values.yaml:
  # database.username.existingSecretKey -> "db-user"
  db-user: "gvm"
  
  # database.password.existingSecretKey -> "db-password"
  db-password: "a-very-secure-password"
  
  # database.databaseName.existingSecretKey -> "db-name"
  db-name: "gvmd"
  
  # gvm.adminUser.existingSecretKey -> "admin-user"
  admin-user: "admin"
  
  # gvm.adminPassword.existingSecretKey -> "admin-password"
  admin-password: "gvm-admin-secure-password"
{{- end }}
